//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesManagementSystem_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public string TitleOfCourtesy { get; set; }
        public string City { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public Nullable<System.DateTime> DateOfUpdate { get; set; }
        public string UserName { get; set; }
        public string UserTrnx { get; set; }
        public string IsValid { get; set; }
    }
}
